### ISSUE TITLE
Why are CNVM page links all Google queries?

### ISSUE THREAD

**Issue by athornton** [gonkulator/cnvm#7]
At enteon.com/cnvm: see, for instance, the Open and Shared sections (but it's all the links).  They look like:

https://www.google.com/url?q=http://www.linuxfoundation.org/&sa=D&usg=AFQjCNHe5YcDR6SiZJhb60_toEt-PD8inw

If this is SEO, it's a pretty unsubtle way of doing it.

(reported to me by Andy Latham)

**Comment by fl0yd** [comment]
Adjusted... thanks Andy.
